### ISSUE TITLE
Add option to notify in Slack

### ISSUE THREAD

**Issue by mokit** [wieni/lola#8]

**Comment by spoit** [comment]
* Do you want this to go to one specific channel (eg. #lola) or should this be configurable per lola.yaml/env/stack/...
* This will mean putting a slack integration api key (or whatever) in  _every_ lola.yml file.. can be cumbersome

**Comment by mokit** [comment]
1 room is enough

#lola

**Comment by spoit** [comment]
Proposal:

```yml
slack:
  enabled: true
  key: <slack api key>
  channel: <slack_channel> 
```

This happens on the root level, every lola will then be logged to the channel. You can override on the lower levels (environment-stack) with:

```yml
<environment>:
  <stack>:
    slack:
      enabled: false
```

Another idea is to allow _functions on _all_actions, like hooks. Then you can plugin whatever-you-want via custom functions...
